---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculate-v1
  labels:
    app: calculate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculate
  template:
    metadata:
      labels:
        app: calculate
    spec:
      containers:
      - name: calculate
        image: nutslove/fastapi-calculate:v1
        imagePullPolicy: Always